import type { GameConfig } from './types';

export const GAME_CONFIG: GameConfig = {
  renderer: {
    clearColor: 0xf0b46a,
    fogColor: 0xd89054,
    fogNear: 28,
    fogFar: 170,
  },
  player: {
    maxHealth: 100,
    eyeHeight: 1.65,
    forwardSpeed: 18,
    strafeSpeed: 10.5,
    roadHalfWidth: 9,
    collisionRadius: 0.9,
    mouseSensitivity: 0.0017,
    maxYaw: 1.1,
    minPitch: -0.9,
    maxPitch: 0.75,
    bobAmplitude: 0.045,
    bobFrequency: 0.19,
  },
  weapon: {
    fireRate: 7.5,
    magazineSize: 12,
    reloadDuration: 1.4,
    range: 120,
    damagePerShot: 1,
    recoilKick: 0.055,
    recoilRecovery: 8.5,
  },
  enemies: {
    poolSize: 28,
    spawnMinZ: -120,
    spawnMaxZ: -78,
    cleanupZ: 12,
    contactRadius: 1.35,
    types: {
      walker: {
        type: 'walker',
        speed: 2.3,
        maxHealth: 1,
        contactDamage: 11,
        scoreValue: 10,
        scale: 1,
        bodyColor: 0x6e9f57,
        accentColor: 0x2c3a2f,
        spawnWeight: 1,
      },
      runner: {
        type: 'runner',
        speed: 4.6,
        maxHealth: 1,
        contactDamage: 16,
        scoreValue: 20,
        scale: 0.86,
        bodyColor: 0xc67d3b,
        accentColor: 0x4b2a1d,
        spawnWeight: 0,
      },
      tank: {
        type: 'tank',
        speed: 1.65,
        maxHealth: 4,
        contactDamage: 28,
        scoreValue: 50,
        scale: 1.5,
        bodyColor: 0x8e4a4a,
        accentColor: 0x2c1717,
        spawnWeight: 0,
      },
    },
  },
  spawn: {
    rampDuration: 60,
    intervalStart: 1.3,
    intervalEnd: 0.52,
    batchChance: 0.3,
  },
  world: {
    roadWidth: 22,
    roadHalfWidth: 11,
    laneCenters: [-5.6, 0, 5.6],
    chunkLength: 40,
    chunkCount: 6,
    obstaclePoolSize: 16,
    obstacleSpacingMin: 18,
    obstacleSpacingMax: 30,
    obstacleCleanupZ: 14,
    obstacleDamage: 12,
    obstacleHitboxDepth: 2.6,
  },
};
