import type { GameConfig } from './types';

export const GAME_CONFIG: GameConfig = {
  debug: {
    developmentWeapons: false,
  },
  renderer: {
    clearColor: 0x0a0f14,
    fogColor: 0x2a333d,
    fogNear: 15,
    fogFar: 72,
    exposure: 1.5,
    atmosphere: {
      rest: {
        clearColor: 0x0b1015,
        fogColor: 0x2d3741,
        fogNear: 15,
        fogFar: 76,
        exposure: 1.5,
        radarStrength: 0.9,
      },
      chaos: {
        clearColor: 0x090e13,
        fogColor: 0x29323c,
        fogNear: 14,
        fogFar: 70,
        exposure: 1.45,
        radarStrength: 0.86,
      },
      dark: {
        clearColor: 0x080d12,
        fogColor: 0x263039,
        fogNear: 13,
        fogFar: 66,
        exposure: 1.35,
        radarStrength: 0.7,
      },
    },
  },
  player: {
    maxHealth: 100,
    eyeHeight: 1.65,
    forwardSpeed: 18,
    strafeSpeed: 10.5,
    roadHalfWidth: 9,
    collisionRadius: 0.9,
    mouseSensitivity: 0.0017,
    maxYaw: 1.1,
    minPitch: -0.9,
    maxPitch: 0.75,
    bobAmplitude: 0.045,
    bobFrequency: 0.19,
    leanRange: 1.35,
    leanResponsiveness: 8.8,
    wigglePulse: 0.38,
    wiggleDecay: 0.34,
    wiggleMaxInterval: 0.28,
    latchAimShake: 0.035,
    failureAimShake: 0.0112,
  },
  vehicle: {
    engineAudioPath: '/audio/vehicle/engine-sound.ogg',
    engineVolume: 0.075,
    enginePlaybackRate: 0.95,
    engineHighpassHz: 120,
    engineLowpassHz: 1850,
    stallAudioPath: '/audio/vehicle/motor-ngadat.ogg',
    stallAudioVolume: 0.16,
    stallAudioPlaybackRate: 1,
    turnVolume: 0.038,
    turnPlaybackRate: 0.84,
    turnLowpassHz: 780,
    turnEnterSmoothing: 0.08,
    turnReleaseSmoothing: 0.24,
    stage1Rig: {
      position: [0, 0, 0],
      assetPath: '/models/vehicles/Motorcycle+sidecar.glb',
      fallbackAssetPath: '/models/vehicles/sidecar-motorcycle-chaos-fallback.glb',
      modelPosition: [-0.12, -0.35, -0.12],
      modelRotationDegrees: [0,45  , 0],
      modelScale: 1.02,
      seatPivotPosition: [0.10, -0.25, 0.10],
      cameraOffset: [-0.035, 0.035, 0.12],
      roleProfiles: {
        gunner: {
          seatPivotPosition: [0.10, -0.25, 0.10],
          cameraOffset: [-0.035, 0.035, 0.12],
          cameraLookAtOffset: [0, 0, 0],
        },
        driver: {
          seatPivotPosition: [0.58, -0.28, -0.06],
          cameraOffset: [0.08, 0.02, 0.04],
          cameraLookAtOffset: [0, 0, 0],
        },
      },
      wheelSpinAxis: 'z',
      wheelSpinMultiplier: 3.7,
      wheelNodePatterns: ['wheel', 'tire', 'tyre', 'roda', 'ban'],
      poseNodePatterns: {
        driverArm: ['driver', 'joe', 'arm'],
        driverHand: ['driver', 'joe', 'hand', 'pistol'],
        gunnerArm: ['gunner', 'police', 'arm'],
        gunnerHand: ['gunner', 'police', 'hand', 'weapon', 'pistol', 'shotgun', 'bazooka'],
      },
      localGunnerHiddenNodePatterns: ['police_body', 'police_arms'],
      posePulseDuration: 0.18,
      driverFirePoseDegrees: [8, 0, -10],
      gunnerFirePoseDegrees: [-10, 0, 8],
      driverWorldMuzzleOffset: [0.16, 0.02, -0.06],
      gunnerWorldMuzzleOffset: [0.22, 0.03, -0.08],
      gunnerLookDownModelOffset: [0, -0.42, -0.18],
      gunnerLookDownModelOffsetStartDegrees: 12,
      lookDownReveal: [0.055, -0.15, 0.2],
      swayAmplitude: [0.005, 0.004, 0.003],
      swayFrequency: 1.65,
      vibrationAmplitude: 0.0017,
      vibrationFrequency: 23,
      turnShift: 0.018,
      turnRollDegrees: 1.2,
      damageShakeAmplitude: 0.02,
      damageShakeDecay: 10,
      laneShift: 0.12,
      laneRollDegrees: 2.9,
      failureShakeAmplitude: 0.0072,
      latchShakeAmplitude: 0.016,
      sidecarLatchPosition: [-1.00, -1.96, -1.25],
      headlightPosition: [-1.5, -1.38, -1.35],
      headlightTargetPosition: [0, -0.7, -13.8],
      headlightColor: 0xfff1d6,
      headlightIntensity: 9.5,
      headlightDistance: 14.5,
      headlightAngleDegrees: 44,
      headlightPenumbra: 1.92,
      headlightDecay: 2,
      headlightShadowMapSize: 1024,
      headlightShadowBias: -0.00022,
      headlightShadowNormalBias: 0.016,
      headlightFillColor: 0xdde7ff,
      headlightFillIntensity: 4.6,
      headlightFillDistance: 10.5,
      headlightFillAngleDegrees: 74,
      headlightFillPenumbra: 1,
      headlightFillTargetPosition: [0, -0.16, -8.6],
      nearFillPosition: [0, 0.28, 0.24],
      nearFillColor: 0xaec8ff,
      nearFillIntensity: 1.45,
      nearFillDistance: 6.8,
    },
  },
  fpsViewmodels: {
    driver_pistol: {
      path: '/models/viewmodels/driver+pistol.glb',
      position: [0, -0.35, -0.75],
      rotationDegrees: [0, -90, 0],
      scale: 1,
      muzzleOffset: [0.18, 0.02, -0.1],
    },
    gunner_handgun: {
      path: '/models/viewmodels/police+handgun.glb',
      position: [0, -0.35, -0.45],
      rotationDegrees: [0, -85, 0],
      scale: 1,
      muzzleOffset: [0.18, 0.02, -0.1],
    },
    gunner_shotgun: {
      path: '/models/viewmodels/police+shotgun.glb',
      position: [0, -0.38, -0.85],
      rotationDegrees: [0, -70, 0],
      scale: 1,
      muzzleOffset: [0.28, 0.02, -0.16],
    },
    gunner_bazooka: {
      path: '/models/viewmodels/police+bazooka.glb',
      position: [0, -0.42, -0.9],
      rotationDegrees: [0, -70, 0],
      scale: 1,
      muzzleOffset: [0.35, 0.03, -0.18],
    },
  },
  ride: {
    lowHealthThreshold: 0.35,
    criticalHealthThreshold: 0.25,
    failureHandlingPenalty: 0.4,
    failureSpeedPenalty: 0.18,
    potholeShakeDuration: 0.75,
    potholeAimShake: 0.035,
    brokenLaneHandlingPenalty: 0.22,
    brokenLaneDamage: 8,
    brokenLaneShake: 0.025,
    latchSpeedMultiplier: 0.58,
    latchCameraShake: 0.022,
    latchAimShake: 0.045,
    latchWiggleRequired: 5.4,
    latchShotgunBonusDamage: 2,
    brakeDuration: 0.9,
    brakeSpeedMultiplier: 0.72,
    boostDuration: 1.2,
    boostSpeedMultiplier: 1.24,
    inputCooldown: 2.2,
    inputHoldResponse: 10,
    brakeMeterDrainRate: 0.72,
    brakeMeterRechargeRate: 0.36,
    boostMeterDrainRate: 0.64,
    boostMeterRechargeRate: 0.32,
    adrenalineAimShakeMultiplier: 0.68,
    adrenalineReloadMultiplier: 0.84,
    adrenalineWiggleMultiplier: 1.35,
    nitroBoostMultiplier: 1.18,
    nitroSpeedBonus: 0.08,
    nitroLaneChangeMultiplier: 0.86,
  },
  driver: {
    promptIntervalMin: 8,
    promptIntervalMax: 16,
    promptDuration: 2.8,
    laneRequestHoldDuration: 0.40,
    laneRequestCooldown: 1.00,
    laneRequestMisreadChance: 0.22,
    opportunityPromptCooldown: 8,
    blockerVetoDistance: 24,
    criticalFailureVetoSeverity: 0.82,
    pickupWindowDistance: 36,
    pickupAutoValueThreshold: 1.05,
    pickupPromptValueThreshold: 1.5,
    pickupAutoMaxCost: 2.1,
    pickupPromptMaxCost: 3.25,
    laneRescanInterval: 0.45,
    laneChangeDuration: 0.46,
    laneChangeCommitDuration: 0.3,
    promptEffectLockout: 3.6,
    scoreMarginToChange: 1.2,
    floorItDuration: 2.35,
    floorItSpeedMultiplier: 1.18,
    floorItAimShake: 0.018,
    floorItCameraShake: 0.026,
    floorItOpportunityBonus: 0.82,
    floorItPickupDistance: 30,
    brakeDuration: 1.8,
    brakeSpeedMultiplier: 0.82,
    brakeStabilityBonus: 0.12,
    brakeAimShake: 0.004,
    brakeCameraShake: 0.01,
    brakeHazardDistance: 22,
    engineTroubleDuration: 2.7,
    engineTroubleForcedDuration: 1.9,
    engineTroubleSpeedMultiplier: 0.76,
    engineTroubleAimShake: 0.044,
    engineTroubleCameraShake: 0.05,
    engineTroubleWobbleAmplitude: 0.095,
    engineTroubleWobbleFrequency: 10.5,
    engineTroubleFailureThreshold: 0.38,
    cautiousHoldDuration: 1.8,
    supportCueDuration: 1.15,
    supportCueCooldown: 3.4,
  },
  pacing: {
    sequence: ['rest', 'chaos', 'dark'],
    durations: {
      rest: 18,
      chaos: 24,
      dark: 18,
    },
    spawnIntervalMultiplier: {
      rest: 1.04,
      chaos: 0.9,
      dark: 0.96,
    },
    batchChanceBonus: {
      rest: -0.04,
      chaos: 0.08,
      dark: 0.02,
    },
    enemyLaneThreatBonus: {
      rest: -0.08,
      chaos: 0.22,
      dark: 0.12,
    },
    hazardDensity: {
      rest: 0.8,
      chaos: 1.28,
      dark: 1.05,
    },
    visibility: {
      rest: 1,
      chaos: 0.88,
      dark: 0.52,
    },
    events: {
      warmup: 10,
      intervalMin: 15,
      intervalMax: 23,
      durationMin: 7,
      durationMax: 11,
      blackoutRadarMultiplier: 0.42,
      blackoutFogMultiplier: 1.44,
      slipperyHandlingPenalty: 0.08,
      slipperyPulseEffectiveness: 0.9,
      slipperyLaneChangeMultiplier: 1.05,
      berserkSpawnMultiplier: 0.72,
      berserkBatchBonus: 0.22,
      berserkRunnerBonus: 0.05,
    },
  },
  weapon: {
    fireRate: 7.5,
    magazineSize: 12,
    reloadDuration: 1.45,
    range: 120,
    damagePerShot: 1,
    cameraKick: 0.04,
    recoilRecovery: 8.5,
    tracer: {
      duration: 0.06,
      width: 0.018,
      glowWidth: 0.045,
      color: 0xfff0de,
      glowColor: 0xffad63,
      opacity: 0.88,
      missLength: 42,
    },
    audio: {
      gunshotPath: '/audio/weapons/9mm-gunshot.ogg',
      emptyPath: '/audio/weapons/no-ammo.ogg',
      reloadPath: '/audio/weapons/reload.ogg',
      gunshotVolume: 0.1,
      emptyVolume: 0.14,
      reloadVolume: 0.36,
    },
    viewmodel: {
      assetPath: '/models/weapons/pistol-web.glb',
      position: [0.34, -0.45, -0.64],
      rotationDegrees: [1.5, -95, -1.2],
      scale: 0.34,
      recoilBack: 0.065,
      recoilLift: 0.014,
      recoilPitchDegrees: 7,
      recoilRollDegrees: 5,
      recoilRecovery: 14,
      slideTravel: 0.055,
      slideRecovery: 18,
      magazineDrop: 0.2,
      magazineTiltDegrees: 34,
      reloadSideShift: 0.12,
      reloadLift: 0.11,
      reloadPushBack: 0.025,
      reloadTiltDegrees: -30,
      muzzleOffset: [0, 0.30, 0],
      muzzleFlashSize: 0.21,
      muzzleFlashDuration: 0.085,
    },
  },
  shotgun: {
    fireRate: 0.95,
    maxAmmo: 6,
    range: 34,
    pelletsPerShot: 12,
    damagePerPellet: 1,
    spread: 0.4,
    spreadKick: 0.25,
    cameraKick: 0.22,
    pelletVisualCount: 6,
    pelletTraceMinLength: 8,
    pelletTraceMaxLength: 32,
    pelletTraceDuration: 0.30,
    pelletTraceMuzzleForward: 2.15,
    audio: {
      gunshotPath: '/audio/weapons/shotgun-shot.ogg',
      delayPath: '/audio/weapons/shotgun-delay.ogg',
      gunshotVolume: 0.14,
      delayVolume: 0.1,
    },
    viewmodel: {
      assetPath: '/models/weapons/shotgun-web.glb',
      muzzleFlashSpritePath: '/sprites/shotgun-muzzle-flash.png',
      position: [0.54, -0.66, -1.02],
      rotationDegrees: [2.6, -92, -1.4],
      scale: 1.2,
      recoilBack: 0.22,
      recoilLift: 0.05,
      recoilPitchDegrees: 14,
      recoilRollDegrees: 7,
      recoilRecovery: 3.9,
      pumpTravel: 0.14,
      pumpRecovery: 3.4,
      pumpDelay: 0.16,
      spinDuration: 0.42,
      spinTurns: 1,
      muzzleOffset: [0, 0, 0],
      muzzleFlashSpriteOffset: [-2.92, -0.80, 1],
      muzzleBlastOffset: [0, 0, 0],
      muzzleFlashSize: 0.52,
      muzzleFlashDuration: 0.14,
    },
  },
  bazooka: {
    maxAmmo: 1,
    rocketSpeed: 58,
    rocketRadius: 1.05,
    maxDistance: 92,
    explosionRadius: 9.5,
    tankDamage: 3,
    smokeSpawnInterval: 0.026,
    smokeLifetime: 0.48,
    smokeStartSize: 0.18,
    smokeEndSize: 0.62,
    smokeDrift: 0.4,
    cameraKick: 0.3,
    audio: {
      launchPath: '/audio/weapons/bazooka-launch.ogg',
      impactPath: '/audio/weapons/bazooka-impact.ogg',
      launchVolume: 0.16,
      impactVolume: 0.22,
      launchPlaybackRate: 1,
    },
    viewmodel: {
      assetPath: '/models/weapons/bazooka-web.glb',
      fallbackAssetPath: '/models/weapons/bazooka.glb',
      position: [0.40, -0.25, -0.88],
      rotationDegrees: [4, -92, -2.2],
      scale: 0.92,
      recoilBack: 0.16,
      recoilLift: 0.04,
      recoilPitchDegrees: 9,
      recoilRecovery: 4.2,
      muzzleOffset: [-1.34, 0.2, 0],
      muzzleFlashSize: 0.9,
      muzzleFlashDuration: 0.12,
    },
  },
  enemies: {
    poolSize: 28,
    spawnMinZ: -120,
    spawnMaxZ: -78,
    cleanupZ: 12,
    contactRadius: 1.35,
    audio: {
      normalDeathPath: '/audio/enemies/normal-zombie-death.ogg',
      tankDeathPath: '/audio/enemies/tank-zombie-death.ogg',
      approachPath: '/audio/enemies/zombie-approaching.ogg',
      normalDeathVolume: 0.36,
      tankDeathVolume: 0.42,
      approachVolume: 0.24,
      approachDistance: 2.55,
      approachCooldown: 0.42,
    },
    walkerModel: {
      characterPath: '/models/enemies/walker/character.glb',
      textureMaterialPath: '/models/enemies/walker/texture-web.glb',
      moveAnimationPath: '/models/enemies/walker/walk.glb',
      deathAnimationPath: '/models/enemies/walker/death.glb',
      position: [0, 0, 0],
      rotationDegrees: [0, 0, 0],
      scale: 1.5,
      moveAnimationSpeed: 1.16,
      deathAnimationSpeed: 6.2,
      fadeDelay: 0.3,
      fadeDuration: 0.55,
      fadeSink: 0.18,
      hitBloodCount: 12,
      hitBloodSize: 1.5,
      hitBloodSpeed: 4.6,
      hitBloodLifetime: 0.42,
      bodySplatterCount: 10,
      bodySplatterSize: 0.12,
      bodySplatterSpeed: 4.4,
      bodySplatterLifetime: 0.18,
      bloodDelay: 0,
      bloodBurstCount: 7,
      bloodBurstSize: 0.085,
      bloodBurstSpeed: 2.8,
      bloodBurstLifetime: 0.42,
      bloodGravity: 10.5,
      roadSplatSize: 0.32,
      roadSplatLifetime: 2.6,
      roadSplatOpacity: 0.82,
    },
    runnerModel: {
      characterPath: '/models/enemies/runner/character.glb',
      textureMaterialPath: '/models/enemies/runner/texture-web.glb',
      moveAnimationPath: '/models/enemies/runner/move.glb',
      deathAnimationPath: '/models/enemies/runner/death.glb',
      position: [0, 0, 0],
      rotationDegrees: [0, 0, 0],
      scale: 1.48,
      moveAnimationSpeed: 1.2,
      deathAnimationSpeed: 6.8,
      fadeDelay: 0.28,
      fadeDuration: 0.5,
      fadeSink: 0.16,
      hitBloodCount: 12,
      hitBloodSize: 0.3,
      hitBloodSpeed: 5.2,
      hitBloodLifetime: 0.42,
      bodySplatterCount: 10,
      bodySplatterSize: 0.11,
      bodySplatterSpeed: 5.0,
      bodySplatterLifetime: 0.18,
      bloodDelay: 0,
      bloodBurstCount: 7,
      bloodBurstSize: 0.082,
      bloodBurstSpeed: 3.1,
      bloodBurstLifetime: 0.42,
      bloodGravity: 10.8,
      roadSplatSize: 0.3,
      roadSplatLifetime: 2.4,
      roadSplatOpacity: 0.8,
      latchPresentationPath: '/models/enemies/runner/latch-grab.glb',
      latchMountPosition: [0, 0, 0],
      latchMountRotationDegrees: [15, 112, -18],
      latchPresentationPosition: [0.08, -1.22, 0.1],
      latchPresentationRotationDegrees: [24, -88, 0],
      latchPresentationScale: 1.08,
    },
    tankModel: {
      characterPath: '/models/enemies/tank/character.glb',
      textureMaterialPath: '/models/enemies/tank/texture-web.glb',
      moveAnimationPath: '/models/enemies/tank/move.glb',
      deathAnimationPath: '/models/enemies/tank/death.glb',
      spawnPoseAnimationPath: '/models/enemies/tank/pose.glb',
      spawnPoseChance: 0.38,
      spawnPoseDuration: 0.8,
      spawnPoseSpeed: 1.55,
      spawnPoseMoveSpeedMultiplier: 0.35,
      position: [0, 0, 0],
      rotationDegrees: [0, 0, 0],
      scale: 1.68,
      moveAnimationSpeed: 1.9,
      deathAnimationSpeed: 5.6,
      fadeDelay: 0.35,
      fadeDuration: 0.62,
      fadeSink: 0.18,
      hitBloodCount: 14,
      hitBloodSize: 0.18,
      hitBloodSpeed: 4.6,
      hitBloodLifetime: 0.48,
      bodySplatterCount: 13,
      bodySplatterSize: 0.14,
      bodySplatterSpeed: 4.4,
      bodySplatterLifetime: 0.22,
      bloodDelay: 0.04,
      bloodBurstCount: 9,
      bloodBurstSize: 0.1,
      bloodBurstSpeed: 2.9,
      bloodBurstLifetime: 0.48,
      bloodGravity: 11.2,
      roadSplatSize: 0.42,
      roadSplatLifetime: 2.8,
      roadSplatOpacity: 0.84,
    },
    types: {
      walker: {
        type: 'walker',
        label: 'Standard',
        speed: 2.3,
        maxHealth: 1,
        contactDamage: 11,
        scoreValue: 10,
        scale: 1,
        bodyColor: 0x6e9f57,
        accentColor: 0x2c3a2f,
        spawnWeight: 1,
        laneThreat: 1.05,
        canBeRammed: true,
      },
      runner: {
        type: 'runner',
        label: 'Runner',
        speed: 5.1,
        maxHealth: 1,
        contactDamage: 16,
        scoreValue: 20,
        scale: 0.86,
        bodyColor: 0xc67d3b,
        accentColor: 0x4b2a1d,
        spawnWeight: 0,
        laneThreat: 1.22,
        canBeRammed: true,
      },
      tank: {
        type: 'tank',
        label: 'Brute',
        speed: 1.65,
        maxHealth: 4,
        contactDamage: 28,
        scoreValue: 50,
        scale: 1.5,
        bodyColor: 0x8e4a4a,
        accentColor: 0x2c1717,
        spawnWeight: 0,
        laneThreat: 2.9,
        canBeRammed: false,
      },
    },
  },
  spawn: {
    rampDuration: 72,
    intervalStart: 1.14,
    intervalEnd: 0.7,
    batchChance: 0.22,
    laneGroupChance: 0.12,
    runnerCooldownMin: 5.2,
    runnerCooldownMax: 6.8,
    runnerMaxActive: 2,
  },
  world: {
    roadWidth: 22,
    roadHalfWidth: 11,
    laneCenters: [-5.6, 0, 5.6],
    chunkLength: 40,
    chunkCount: 6,
    obstaclePoolSize: 18,
    obstacleSpacingMin: 13,
    obstacleSpacingMax: 22,
    obstacleCleanupZ: 14,
    obstacleDamage: 12,
    wreckSpawnWeight: 0.8,
    obstacleHitboxDepth: 2.6,
    roadSurfaceY: -0.18,
    roadCurveAmplitude: 0.65,
    roadCurveFrequency: 0.016,
    roadsidePropDensity: 1,
    brokenLane: {
      width: 4.6,
      depth: 4.8,
      damage: 8,
      handlingPenalty: 0.22,
      aimShake: 0.028,
      spawnWeight: 0.82,
    },
    pothole: {
      width: 2.1,
      depth: 2.4,
      damage: 2,
      handlingPenalty: 0.1,
      aimShake: 0.036,
      spawnWeight: 0.92,
    },
    barricade: {
      assetPath: '/models/obstacles/barricade/barricade-web.glb',
      scale: 1.24,
      yOffset: 0.10,
      tintColor: 0xbcb5ab,
      width: 2.65,
      depth: 1.18,
      collisionDamage: 12,
      spawnWeight: 1.55,
    },
    concreteBlock: {
      assetPath: '/models/obstacles/concrete-block/concrete-block-web.glb',
      scale: 1.22,
      yOffset: 0.14,
      tintColor: 0xa8a7a1,
      width: 2.42,
      depth: 1.48,
      collisionDamage: 14,
      spawnWeight: 1.3,
    },
    car: {
      assetPath: '/models/obstacles/car/car-web.glb',
      fallbackAssetPath: '/models/obstacles/car/car-base.glb',
      scale: 4.00,
      yOffset: 0.05,
      width: 5.25,
      depth: 3.2,
      collisionDamage: 18,
      spawnChance: 0.36,
      spawnSpacingMin: 132,
      spawnSpacingMax: 188,
    },
    barrel: {
      assetPath: '/models/obstacles/barrel/barrel-web.glb',
      scale: 0.58,
      tintColor: 0x5e4d3c,
      spawnChance: 0.1,
      spawnSpacingMin: 42,
      spawnSpacingMax: 68,
      collisionDamage: 10,
      explosionRadius: 7.2,
      tankDamage: 2,
      flashDuration: 0.28,
      flashSize: 3.8,
    },
    audio: {
      obstacleImpactPath: '/audio/world/concrete-barrier-crack.ogg',
      obstacleImpactVolume: 0.72,
      barrelExplosionPath: '/audio/world/barrel-exploding.ogg',
      barrelExplosionVolume: 0.24,
    },
    breakEffect: {
      pieceCount: 8,
      dustCount: 3,
      lifetime: 0.48,
      gravity: 15,
      horizontalSpeed: 2.8,
      upwardSpeed: 2.45,
      pieceSize: 0.22,
      dustSize: 0.4,
    },
  },
  pickups: {
    supportUnlockTimeSeconds: 15,
    unlockTimeSeconds: 30,
    bazookaUnlockTimeSeconds: 45,
    poolSize: 12,
    spawnMinZ: -126,
    spawnMaxZ: -92,
    cleanupZ: 16,
    hitboxDepth: 2.4,
    shotgunPickupAmmo: 6,
    shotgunPickupSpacingMin: 68,
    shotgunPickupSpacingMax: 96,
    ammoCrateSpacingMin: 42,
    ammoCrateSpacingMax: 70,
    ammoCrateChance: 0.76,
    ammoCrateMin: 2,
    ammoCrateMax: 4,
    bazookaSpawnChance: 0.22,
    bazookaPickupSpacingMin: 86,
    bazookaPickupSpacingMax: 124,
    shotgunPickupScale: 0.78,
    ammoCrateScale: 1,
    bazookaPickupScale: 0.9,
    supportPickupScale: 1.05,
    supportPickupSpacingMin: 34,
    supportPickupSpacingMax: 58,
    supportPickupChance: 0.42,
    medkitEarliestSeconds: 45,
    medkitHeal: 30,
    medkitLowHealthBias: 0.38,
    criticalMedkitGraceMin: 3,
    criticalMedkitGraceMax: 5.5,
    criticalMedkitCooldown: 20,
    adrenalineDuration: 8,
    nitroDuration: 3,
    nitroEarliestSeconds: 18,
    audio: {
      pickupPath: '/audio/gameplay/item-pickup.ogg',
      pickupVolume: 0.24,
    },
  },
  rewards: {
    chainDuration: 2.2,
    calloutDuration: 1.05,
    chainLostCalloutDuration: 0.75,
    doubleKillWindow: 0.45,
    tripleKillWindow: 0.6,
    milestoneTimes: [15, 30, 45, 60],
    milestoneValues: [50, 75, 100, 125],
    repeatingMilestoneEvery: 30,
    repeatingMilestoneValue: 150,
    explosiveBonusPerExtraKill: 20,
    dangerKillDistance: 4,
    dangerKillBonus: 10,
    tankDangerKillBonus: 20,
    multiplierThresholds: [
      { kills: 1, multiplier: 1 },
      { kills: 3, multiplier: 1.25 },
      { kills: 5, multiplier: 1.5 },
      { kills: 8, multiplier: 1.75 },
      { kills: 12, multiplier: 2 },
      { kills: 18, multiplier: 2.5 },
      { kills: 25, multiplier: 3 },
    ],
    bonuses: {
      doubleKill: 25,
      tripleKill: 60,
      multiKill: 100,
    },
    accolades: {
      displayDuration: 1.65,
      soundCooldown: 5.75,
      tankDownCooldown: 32,
      latchClearCooldown: 24,
      roadWipeKillCount: 5,
      roadWipeExplosiveKillCount: 4,
      survivalTimes: [60, 90],
      chainThresholds: [12, 25],
    },
    audio: {
      rewardPath: '/audio/gameplay/reward-industrial.ogg',
      rewardVolume: 0.26,
    },
  },
};
